#data config
data_path: "C:/Users/Dolly/Documents/A.Study/data/test/kidney_left_test_data" #data path of images to be inferred 
data_list: "./configs/kidney/data_list_kidney_test.txt" #.txt file containing images to be predicted

#model config
model_path: "C:/Users/Dolly/Documents/A.Study/models/noise2inverse_organised/full_image_pag/kidney_scan_all_20230723-010507/weights" #the model checkpoint directory
checkpoint_name: "weights_epoch_10_0.00.torch"
num_splits: 2
strategy: "X:1" # "i:X"
data_scaling: 65536 #65536 #for normalisation
n_features: 32
network: "unet" # "msd", "unet", "dncnn"

multi_gpu: False

input_channels: 1 #more for 2.5D
gpu_id: 0 #set which gpu to use when not using multi_gpu

#prediction config  
save_split_pred: True #save the split predictions